name: GUI CI with Chrome, VNC, AWT and screen recording

on:
  push:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      SEED: ${{ secrets.SEED_PHRASE }}
      PASS: ${{ secrets.PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'liberica'

      - name: Pull Chrome with GUI (AWT-capable)
        run: docker pull selenium/standalone-chrome-debug

      - name: Run Chrome container with GUI and VNC
        run: |
          docker run -d --name selenium \
            -e SEED="$SEED" \
            -e PASS="$PASS" \
            -p 4444:4444 \
            -p 5900:5900 \
            -v ${{ github.workspace }}:/workspace \
            selenium/standalone-chrome-debug

      - name: Wait for Selenium
        run: |
          for i in {1..20}; do
            curl -s http://localhost:4444/wd/hub/status | grep -q '"ready":true' && break
            echo "Waiting for Selenium..."
            sleep 3
          done

      - name: Start screen recording inside container
        run: |
          docker exec -d selenium bash -c '
            apt-get update && apt-get install -y ffmpeg &&
            ffmpeg -y -video_size 1366x768 -framerate 15 -f x11grab -i :99 \
              -codec:v libx264 -pix_fmt yuv420p /workspace/screen_recording.mp4 > /dev/null 2>&1 &
            echo $! > /tmp/ffmpeg_pid.txt
          '

      - name: Run tests with Maven
        run: |
          mvn clean test \
            -DSEED_PHRASE="${SEED}" \
            -DPASSWORD="${PASS}" \
            -Dselenium.remote.url=http://localhost:4444/wd/hub

      - name: Stop screen recording
        if: always()
        run: docker exec selenium bash -c 'kill -INT $(cat /tmp/ffmpeg_pid.txt); sleep 2'

      - name: Copy screen recording
        if: always()
        run: docker cp selenium:/workspace/screen_recording.mp4 .

      - name: Upload screen recording
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screen-recording
          path: screen_recording.mp4

      - name: Cleanup
        if: always()
        run: docker rm -f selenium
