name: UI Tests with Video & Allure

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      SEED: ${{ secrets.SEED_PHRASE }}
      PASS: ${{ secrets.PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t dapp-tests .

      - name: Run tests in container
        run: |
          docker run --rm \
            -e SEED="${SEED}" \
            -e PASS="${PASS}" \
            -v ${{ github.workspace }}/artifacts:/app/target/allure-results \
            dapp-tests ./entrypoint.sh

      - name: Upload video
        uses: actions/upload-artifact@v4
        with:
          name: screen-recording
          path: artifacts/screen_recording.mp4

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: artifacts/

      - name: Generate Allure report
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: artifacts
          allure_history: allure-history

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
