name: GUI CI with screen recording

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DISPLAY: :99
      SEED: ${{ secrets.SEED_PHRASE }}
      PASS: ${{ secrets.PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'liberica'

      - name: Install tools (Xvfb + ffmpeg)
        run: sudo apt-get update && sudo apt-get install -y xvfb ffmpeg x11-utils

      - name: Start Xvfb
        run: |
          Xvfb :99 -screen 0 1366x768x24 &
          sleep 3

      - name: Start recording screen with ffmpeg
        run: |
          ffmpeg -y -video_size 1366x768 -framerate 15 -f x11grab -i :99 -codec:v libx264 -pix_fmt yuv420p screen_recording.mp4 > /dev/null 2>&1 &
          echo $! > ffmpeg_pid.txt

      - name: Run UI tests
        run: |
          mvn clean test -DSEED_PHRASE="$SEED" -DPASSWORD="$PASS"

      - name: Stop screen recording
        if: always()
        run: |
          kill -INT $(cat ffmpeg_pid.txt)
          sleep 2

      - name: Upload screen recording
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screen-recording
          path: screen_recording.mp4

      - name: Move screen recording to allure-results
        if: always()
        run: |
          mkdir -p target/allure-results
          cp screen_recording.mp4 target/allure-results/
